name: Create Release

on:
  push:
    branches:
      - main
  
jobs:
  Release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.semver.outputs.next }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Changelog
        run: bash .github/workflows/changelog.sh
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          noVersionBumpBehavior: silent
      - name: Echo Tag
        run: echo ${{ steps.semver.outputs.next }}
      - name: Create Release
        if: ${{ steps.semver.outputs.next }}
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.semver.outputs.next }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
  
  trigger_build:
    needs: Release
    if: ${{ needs.Release.outputs.output1 != 0 }}
    uses: ./.github/workflows/build_packages.yml